const now = '2026-04-17T12:00:00.000Z';

export const GUIDE_SEED_DOCUMENTS = [
  {
    id: 'guide-kyoto-spring',
    scope: 'international',
    title: '京都春日赏樱旅行攻略',
    summary: '围绕清水寺、哲学之道与岚山的一条轻松赏樱路线，适合 3 天慢游。',
    coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/kyoto-spring',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-03-01',
    destinationLabel: '京都',
    tags: ['赏樱', '春季', '3天'],
    fetchedAt: now,
    blocks: [
      { id: 'kyoto-1', type: 'section-title', text: '最佳季节' },
      { id: 'kyoto-2', type: 'paragraph', text: '3 月下旬到 4 月上旬是京都樱花观赏高峰，建议至少提前 4 周预订酒店。' },
      { id: 'kyoto-3', type: 'section-title', text: '推荐节奏' },
      { id: 'kyoto-4', type: 'paragraph', text: '如果是第一次去京都赏樱，建议把行程控制在 3 天，留出半天机动时间应对天气和热门景点排队。' },
      { id: 'kyoto-5', type: 'section-title', text: '推荐路线' },
      { id: 'kyoto-6', type: 'bullet-list', text: '清水寺 - 二年坂 - 哲学之道 - 冈崎公园 - 岚山' },
      { id: 'kyoto-7', type: 'paragraph', text: '第一天更适合放在东山一带慢慢步行，第二天清晨去哲学之道，第三天把岚山和嵯峨野安排在一起会更顺。' },
      { id: 'kyoto-8', type: 'section-title', text: '住宿建议' },
      { id: 'kyoto-9', type: 'paragraph', text: '想兼顾交通和夜间散步体验，可以优先看四条河原町、祗园周边；预算有限则可以住到京都站附近。' },
      { id: 'kyoto-10', type: 'section-title', text: '拍照与赏樱体验' },
      { id: 'kyoto-11', type: 'paragraph', text: '清晨 7 点前抵达热门寺社，光线更柔和，人流也明显更少；如果遇到阴天，反而更适合拍樱花细节和街道氛围。' },
      { id: 'kyoto-12', type: 'tips', text: '热门寺社附近建议使用公交 + 步行的方式串联，避开中午最拥挤的时段；夜樱场次需提前确认开放日期。' },
    ],
  },
  {
    id: 'guide-yunnan-roadtrip',
    scope: 'domestic',
    title: '云南自驾攻略：大理、丽江、香格里拉 6 日线',
    summary: '覆盖大理古城、洱海、玉龙雪山与独克宗古城的经典云南路线。',
    coverImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/yunnan-roadtrip',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-02-18',
    destinationLabel: '云南',
    tags: ['自驾', '高原', '6天'],
    fetchedAt: now,
    blocks: [
      { id: 'yunnan-1', type: 'section-title', text: '路线概览' },
      { id: 'yunnan-2', type: 'paragraph', text: '建议从大理进、香格里拉出，逐步适应海拔变化，减少高反风险。' },
      { id: 'yunnan-3', type: 'section-title', text: '推荐日程' },
      { id: 'yunnan-4', type: 'bullet-list', text: 'Day 1 大理古城 - Day 2 洱海环线 - Day 3 丽江古城 - Day 4 玉龙雪山 - Day 5 虎跳峡 - Day 6 独克宗古城' },
      { id: 'yunnan-5', type: 'paragraph', text: '这条线路更适合第一次去滇西北、希望同时兼顾古城漫游和自然风景的旅行者，自驾时间整体不算激进。' },
      { id: 'yunnan-6', type: 'section-title', text: '大理与丽江怎么分配' },
      { id: 'yunnan-7', type: 'paragraph', text: '如果你更喜欢松弛感和湖边骑行，可以把时间多留给大理；如果更在意古城、雪山和拍照氛围，丽江至少安排 2 晚更合适。' },
      { id: 'yunnan-8', type: 'section-title', text: '高原与驾驶提醒' },
      { id: 'yunnan-9', type: 'paragraph', text: '从丽江往香格里拉方向海拔会逐步升高，不建议在刚到高原的当天安排强度过高的徒步；山路转弯较多，尽量避免夜间长距离驾驶。' },
      { id: 'yunnan-10', type: 'section-title', text: '住宿建议' },
      { id: 'yunnan-11', type: 'paragraph', text: '大理建议住古城外缘或洱海西线，停车更方便；丽江如果担心古城石板路拖行李麻烦，可以优先看束河附近或新城酒店。' },
      { id: 'yunnan-12', type: 'tips', text: '香格里拉昼夜温差大，4 到 10 月都建议准备薄羽绒；玉龙雪山和热门环海路线旺季最好提前预约。' },
    ],
  },
  {
    id: 'guide-qinghai-lake',
    scope: 'domestic',
    title: '青海湖环线旅行攻略：西宁出发 4 天节奏版',
    summary: '把青海湖、茶卡盐湖与祁连草原串在一起，适合第一次去西北的轻松环线。',
    coverImageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/qinghai-lake-loop',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-04-05',
    destinationLabel: '青海',
    tags: ['青海湖', '西宁', '4天'],
    fetchedAt: now,
    blocks: [
      { id: 'qinghai-1', type: 'section-title', text: '适合人群' },
      { id: 'qinghai-2', type: 'paragraph', text: '适合第一次走西北环线、希望兼顾湖景、公路与草原体验的旅行者。' },
      { id: 'qinghai-3', type: 'section-title', text: '推荐节奏' },
      { id: 'qinghai-4', type: 'bullet-list', text: 'Day 1 西宁 - 日月山 - 青海湖 | Day 2 青海湖东线 - 茶卡盐湖 | Day 3 茶卡 - 祁连草原 | Day 4 祁连 - 西宁' },
      { id: 'qinghai-5', type: 'paragraph', text: '如果你不想把环线开得太赶，这条 4 天版更适合用来感受高原公路和湖景，而不是把所有景点都塞满。' },
      { id: 'qinghai-6', type: 'section-title', text: '沿途重点体验' },
      { id: 'qinghai-7', type: 'paragraph', text: '青海湖适合看开阔湖景和日落，茶卡盐湖更适合晴天拍倒影，祁连草原则更偏向一路开一路停、体验风景变化。' },
      { id: 'qinghai-8', type: 'section-title', text: '住宿建议' },
      { id: 'qinghai-9', type: 'paragraph', text: '第一晚可以住青海湖东侧或黑马河附近，方便第二天继续环线；如果旺季订不到湖边住宿，也可以退到西海镇，整体补给会更稳定。' },
      { id: 'qinghai-10', type: 'section-title', text: '天气与装备' },
      { id: 'qinghai-11', type: 'paragraph', text: '即使是夏天，早晚风也很大，湖边体感温度比西宁更低；长时间在户外拍照时，帽子、墨镜和防晒霜都比想象中更重要。' },
      { id: 'qinghai-12', type: 'tips', text: '高原地区紫外线强，晴天务必准备墨镜、防晒和保温层；如果同行有人第一次上高原，第一天不要安排太晚睡。' },
    ],
  },
];
