const now = '2026-04-17T12:00:00.000Z';

export const GUIDE_SEED_DOCUMENTS = [
  {
    id: 'guide-kyoto-spring',
    scope: 'international',
    title: '京都春日赏樱旅行攻略',
    summary: '围绕清水寺、哲学之道与岚山的一条轻松赏樱路线，适合 3 天慢游。',
    coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/kyoto-spring',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-03-01',
    destinationLabel: '京都',
    tags: ['赏樱', '春季', '3天'],
    fetchedAt: now,
    blocks: [
      { id: 'kyoto-1', type: 'section-title', text: '最佳季节' },
      { id: 'kyoto-2', type: 'paragraph', text: '3 月下旬到 4 月上旬是京都樱花观赏高峰，建议至少提前 4 周预订酒店。' },
      { id: 'kyoto-3', type: 'section-title', text: '推荐路线' },
      { id: 'kyoto-4', type: 'bullet-list', text: '清水寺 - 二年坂 - 哲学之道 - 冈崎公园 - 岚山' },
      { id: 'kyoto-5', type: 'tips', text: '热门寺社附近建议使用公交 + 步行的方式串联，避开中午最拥挤的时段。' },
    ],
  },
  {
    id: 'guide-yunnan-roadtrip',
    scope: 'domestic',
    title: '云南自驾攻略：大理、丽江、香格里拉 6 日线',
    summary: '覆盖大理古城、洱海、玉龙雪山与独克宗古城的经典云南路线。',
    coverImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/yunnan-roadtrip',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-02-18',
    destinationLabel: '云南',
    tags: ['自驾', '高原', '6天'],
    fetchedAt: now,
    blocks: [
      { id: 'yunnan-1', type: 'section-title', text: '路线概览' },
      { id: 'yunnan-2', type: 'paragraph', text: '建议从大理进、香格里拉出，逐步适应海拔变化，减少高反风险。' },
      { id: 'yunnan-3', type: 'bullet-list', text: '大理古城 - 洱海环线 - 丽江古城 - 玉龙雪山 - 虎跳峡 - 独克宗古城' },
      { id: 'yunnan-4', type: 'tips', text: '香格里拉昼夜温差大，4 到 10 月都建议准备薄羽绒。' },
    ],
  },
  {
    id: 'guide-qinghai-lake',
    scope: 'domestic',
    title: '青海湖环线旅行攻略：西宁出发 4 天节奏版',
    summary: '把青海湖、茶卡盐湖与祁连草原串在一起，适合第一次去西北的轻松环线。',
    coverImageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    sourceName: 'Guide API Seed',
    sourceUrl: 'https://guide-api.local/sources/qinghai-lake-loop',
    authorName: 'Voyage Atlas',
    publishedAt: '2026-04-05',
    destinationLabel: '青海',
    tags: ['青海湖', '西宁', '4天'],
    fetchedAt: now,
    blocks: [
      { id: 'qinghai-1', type: 'section-title', text: '适合人群' },
      { id: 'qinghai-2', type: 'paragraph', text: '适合第一次走西北环线、希望兼顾湖景、公路与草原体验的旅行者。' },
      { id: 'qinghai-3', type: 'section-title', text: '推荐节奏' },
      { id: 'qinghai-4', type: 'bullet-list', text: '西宁 - 日月山 - 青海湖 - 茶卡盐湖 - 祁连草原 - 西宁' },
      { id: 'qinghai-5', type: 'tips', text: '高原地区紫外线强，晴天务必准备墨镜、防晒和保温层。' },
    ],
  },
];
